# Generated by Django 4.1.2 on 2022-10-20 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_buying', models.DateField(default=django.utils.timezone.now)),
                ('amount_of_crypto', models.FloatField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='crypto',
            new_name='favorite_crypto',
        ),
        migrations.CreateModel(
            name='CryptoAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency_full_name', models.CharField(default='crypto', max_length=40)),
                ('total_number_of_currency', models.FloatField(default=0)),
                ('buy_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.buyinformation')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='crypto_assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cryptoassets'),
        ),
    ]
