# Generated by Django 4.1.2 on 2022-10-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_buyinformation_rename_crypto_profile_favorite_crypto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoassets',
            name='buy_information',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crypto_assets',
        ),
        migrations.AddField(
            model_name='buyinformation',
            name='CryptoAssets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cryptoassets'),
        ),
        migrations.AddField(
            model_name='cryptoassets',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
