# Generated by Django 4.1.2 on 2022-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_rename_cryptolist_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='MarketCap',
            field=models.BigIntegerField(default=0),
        ),
    ]
