# Generated by Django 4.1.2 on 2022-10-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_cryptocurrency_circulatingsupply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='CirculatingSupply',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='CostInUsd',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='MarketCap',
        ),
    ]
