# Generated by Django 4.1.2 on 2022-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_remove_cryptocurrency_circulatingsupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='CirculatingSupply',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='CostInUsd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='MarketCap',
            field=models.BigIntegerField(default=0),
        ),
    ]
