# Generated by Django 4.1.2 on 2022-10-11 20:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_cryptocurrency_changeprice_cryptocurrency_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='currency_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='UpdateDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 20, 25, 31, 674383, tzinfo=datetime.timezone.utc)),
        ),
    ]
