# Generated by Django 4.1.2 on 2022-10-11 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_cryptocurrency_currency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='UpdateDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 20, 27, 20, 215701, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='currency_id',
            field=models.CharField(default='crypto', max_length=40),
        ),
    ]
