# Generated by Django 4.1.2 on 2022-10-16 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_alter_cryptocurrency_updatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='UpdateDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 16, 17, 2, 54, 563279, tzinfo=datetime.timezone.utc)),
        ),
    ]
