# Generated by Django 4.1.2 on 2022-10-16 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_alter_cryptocurrency_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='UpdateDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 16, 17, 4, 37, 535971, tzinfo=datetime.timezone.utc)),
        ),
    ]
