# Generated by Django 4.1.2 on 2022-10-20 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0022_alter_cryptocurrency_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='UpdateDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
